shots <- teamLoad(removeRow = T,node = ".table-stats",
                  pageUrl = "http://hokej.cz/tipsport-extraliga/stats-center/team-analytic-stats?season=2013&competition=3581")
corsi <- teamLoad(removeRow = F,"http://hokej.cz/tipsport-extraliga/stats-center/team-analytic-stats?season=2013&competition=3581&stats-section=corsi")
faceoff <- teamLoad(removeRow = T,"http://hokej.cz/tipsport-extraliga/stats-center/team-analytic-stats?season=2013&competition=3581&stats-section=faceoff")
wins <- teamLoad(removeRow = T,"http://hokej.cz/tipsport-extraliga/stats-center/team-analytic-stats?season=2013&competition=3581&stats-section=won")
loses <- teamLoad(removeRow = T,"http://hokej.cz/tipsport-extraliga/stats-center/team-analytic-stats?season=2013&competition=3581&stats-section=lost")
goals <- teamLoad(removeRow = T,"http://hokej.cz/tipsport-extraliga/stats-center/team-stats?season=2013&competition=3581")
powerplay <- teamLoad(removeRow = T,"http://hokej.cz/tipsport-extraliga/stats-center/team-stats?season=2013&competition=3581&stats-section=powerplay")
shorthand <- teamLoad(removeRow = T,"http://hokej.cz/tipsport-extraliga/stats-center/team-stats?season=2013&competition=3581&stats-section=shorthanded")
penalty <- teamLoad(removeRow = F,"http://hokej.cz/tipsport-extraliga/stats-center/team-stats?season=2013&competition=3581&stats-section=penalty")
hits <- teamLoad(removeRow = F,"http://hokej.cz/tipsport-extraliga/stats-center/team-stats?season=2013&competition=3581&stats-section=ri")
toi <- teamLoad(removeRow = T,"http://hokej.cz/tipsport-extraliga/stats-center/team-stats?season=2013&competition=3581&stats-section=time")
attendence <- teamLoad(removeRow = F,"http://hokej.cz/tipsport-extraliga/stats-center/team-stats?season=2013&competition=3581&stats-section=visitors")
points <- teamLoad(removeRow = F,node = ".table-soupiska",
                   pageUrl = "http://hokej.cz/tipsport-extraliga/table?table-filter-season=2017&table-filter-competition=6026")
